version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:latest-jdk11
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
